(in-package :bcrawlers)

;; this file will contain all the crawlers for different websites
;; each website we support will have a custom crawler.

(defparameter test-jiji "https://jiji.ug/central-division/mobile-phones/apple-iphone-7-32-gb-rose-gold-yT1Y5dQQ4vzkJvhgPn2w5aUp.html?page=1&pos=1&cur_pos=1&ads_per_page=20&ads_count=20&lid=r-A_VBer8QUqn46VqH")

(defparameter *jiji-types*
  '("cars"
    "buses"
    "heavy-equipment-machinery"
    "motorcycles-and-scooters"
    "trucks-commercial-agricultiral"
    "car-parts-and-accessories"
    "watercrafts-vehicle"
    "new-builds"
    "houses-apartments-for-rent"
    "houses-apartments-for-sale"
    "land-and-plots-for-rent"
    "land-and-plots-for-sale"
    "commercial-property-for-rent"
    "commercial-properties"
    "event-centers-and-venues"
    "mobile-phones"
    "cell-phones-tablets-accessories"
    "smart-watches"
    "tablets"
    "accessories-and-supplies-for-electronics"
    "computers-and-laptops"
    "tv-dvd-equipment"
    "audio-and-music-equipment"
    "computer-accessories"
    "computer-hardware"
    "computer-monitors"
    "headphones"
    "networking-products"
    "cameras-video-cameras-and-accessories"
    "printers-and-scanners"
    "security-and-surveillance"
    "computer-software"
    "videogames"
    "video-games-and-consoles"
    "furniture"
    "garden"
    "decor-accessories"
    "home-appliances"
    "kitchen-appliances"
    "kitchen-and-dining"
    "household-chemicals"
    "bath-body"
    "fragrance"
    "hair-beauty"
    "makeup"
    "sexual-wellness"
    "skin-care"
    "hookah-and-vaporizers"
    "tools-accessories"
    "supplements"
    "bags"
    "clothing"
    "accessories"
    "jewellery-and-watches"
    "shoes"
    "watches"
    "wedding-wear"
    "art-collectibles"
    "books-and-games"
    "camping-gear"
    "cds-and-dvds"
    "musical-instruments"
    "sports-bicycles-and-fitness"
    "accounting-and-finance-cvs"
    "advertising-and-marketing-cvs"
    "arts-and-entertainment-cvs"
    "childcare-and-babysitting-cvs"
    "clerical-and-administrative-cvs"
    "computing-and-it-cvs"
    "construction-and-skilled-trade-cvs"
    "consulting-and-strategy-cvs"
    "customer-service-cvs"
    "driver-cvs"
    "engineering-and-architecture-cvs"
    "farming-and-veterinary-cvs"
    "gardening-and-landscaping-cvs"
    "health-and-beauty-cvs"
    "healthcare-and-nursing-cvs"
    "hotel-cvs"
    "housekeeping-and-cleaning-cvs"
    "human-resources-cvs"
    "internship-cvs"
    "legal-cvs"
    "logistics-and-transportation-cvs"
    "management-cvs"
    "manual-labour-cvs"
    "manufacturing-cvs"
    "mining-industry-cvs"
    "office-cvs"
    "part-time-and-weekend-cvs"
    "quality-control-and-assurance-cvs"
    "quality-control-and-assurance-cvs"
    "research-and-survey-cvs"
    "restaurant-and-bar-cvs"
    "retail-cvs"
    "sales-and-telemarketing-cvs"
    "security-cvs"
    "sports-club-cvs"
    "teaching-cvs"
    "technology-cvs"
    "travel-and-tourism-cvs"
    "other-cvs"
    "automotive-services"
    "building-and-trades-services"
    "chauffeur-and-airport-transfer-services"
    "child-care-and-education-services"
    "classes-and-courses"
    "cleaning-services"
    "computer-and-it-services"
    "dj-and-entertainment-services"
    "fitness-and-personal-training-services"
    "health-and-beauty-services"
    "landscaping-and-gardening-services"
    "legal-services"
    "removals-and-storage-services"
    "manufacturing-services"
    "party-catering-and-event-services"
    "party-catering-and-event-services"
    "pet-services"
    "photography-and-video-services"
    "printing-services"
    "recruitment-services"
    "rental-services"
    "repair-services"
    "tax-and-financial-services"
    "travel-agents-and-tours"
    "wedding-venues-and-services"
    "other-services"
    "accounting-and-finance-jobs"
    "advertising-and-marketing-jobs"
    "arts-and-entertainment-jobs"
    "childcare-and-babysitting-jobs"
    "clerical-and-administrative-jobs"
    "computing-and-it-jobs"
    "construction-and-skilled-trade-jobs"
    "customer-service-jobs"
    "driver-jobs"
    "farming-and-veterinary-jobs"
    "health-and-beauty-jobs"
    "healthcare-and-nursing-jobs"
    "hotel-jobs"
    "housekeeping-and-cleaning-jobs"
    "internship-jobs"
    "logistics-and-transportation-jobs"
    "management-jobs"
    "manual-labour-jobs"
    "office-jobs"
    "part-time-and-weekend-jobs"
    "restaurant-and-bar-jobs"
    "retail-jobs"
    "sales-and-telemarketing-jobs"
    "security-jobs"
    "teaching-jobs"
    "technology-jobs"
    "other-jobs"
    "babies-and-kids-accessories"
    "baby-care"
    "childrens-clothing"
    "childrens-furniture"
    "childrens-gear-and-safety"
    "childrens-shoes"
    "maternity-and-pregnancy"
    "prams-and-strollers"
    "playground-equipment"
    "toys"
    "birds"
    "cats-and-kittens"
    "dogs-and-puppies"
    "fish"
    "pets-accessories"
    "other-animals"
    "reptiles"
    "farm-machinery-equipment"
    "feeds-supplements-seeds"
    "livestock-and-poultry"
    "meals-and-drinks"
    "industrial-ovens"
    "manufacturing-equipments"
    "manufacturing-materials-and-tools"
    "medical-equipment"
    "printing-equipment"
    "restaurant-and-catering-equipment"
    "safety-equipment"
    "salon-equipment"
    "stage-lighting-and-effects"
    "stationery"
    "store-equipments"
    "building-materials"
    "doors"
    "power-equipments"
    "power-tools"
    "hand-and-power-tools"
    "measuring-and-layout-tools"
    "plumbing-and-water-supply"
    "solar-energy-products"
    "windows"
    "other-repair-and-constraction-items")
  "this holds all main pages for the jiji webpage.")

(defun jiji-crawl (type &key (page 1))
  "crawl jiji pages, the data structure being worked is best seen live on the website but this will do
{adverts_list: {adverts: [{image_obj: {url: image-url}, price_title: price, region: region, short_description: desc, title: title, url: url, user_phone: user_phone}]}}"
  (multiple-value-bind (response response-code response-headers request-uri flexi-response response-bool status-text)
      (http-request (format nil "https://jiji.ug/api_web/v1/listing?slug=~a&init_page=true&page=~a&webp=true" type page))
    (let* ((json-data (flexi-streams:octets-to-string response))
	   (data (parse json-data)))
      (hash-get data '("adverts_list" "adverts" 0)))))

(defun save-jiji-item (item)
  "item is a hash table, you need from it an image-url, price_title, region, product url, title"
  (let ((image-url (hash-get item '("image_obj" "url")))
	(gethash "price_title" item)
	(gethash "region" item)
	(gethash "short_description" item)
	(gethash "title" item)
	(gethash "url" item)
	(gethash "region_name" item)
	(gethash "region_parent_name" item)
	(gethash "status" active))
    ))
